blank_issues_enabled: false
contact_links:
  - name: 🗨 Discussions
    url: https://github.com/vinceTheProgrammer/sticknodes-patches/discussions
    about: Unsure if you should start an issue? Search for or start a new discussion!