name: ⭐ Feature request
description: Create a detailed request for a new patch.
title: "[request] "
labels: ["Patch request"]
body:
  - type: markdown
    attributes:
      value: |
        # sticknodes-patches patch request

        Before creating a new patch request, please keep the following in mind:

        - **Do not submit a duplicate patch request**: Search for existing patch requests [here](https://github.com/vinceTheProgrammer/sticknodes-patches/issues?q=label%3A%22Patch+request%22).
        - **Review the contribution guidelines**: Make sure your patch request adheres to it. You can find the guidelines [here](https://github.com/vinceTheProgrammer/sticknodes-patches/blob/main/CONTRIBUTING.md).
        - **Do not use the issue page for support**: If you need help or have questions, get in touch with me on Discord @vincetheanimator or start a new [discussion](https://github.com/vinceTheProgrammer/sticknodes-patches/discussions).
  - type: textarea
    attributes:
      label: Patch description
      description: |
        - Describe your patch in detail
        - Add images, videos, links, examples, references, etc. if possible
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A strong motivation is necessary for a patch request to be considered.

        - Why should this patch be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this patch important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your patch request will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed patch requests and this is not a duplicate
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
